-- Code Workout Web v2 research schema
-- Run this once in Supabase SQL Editor before deploying v2.
-- Safe to rerun: schema and question seeds are idempotent.

create extension if not exists pgcrypto;

create table if not exists public.participants (
  id uuid primary key default gen_random_uuid(),
  participant_code text not null unique,
  created_at timestamptz not null default now(),
  constraint participant_code_format check (participant_code ~ '^[A-Z0-9_-]{1,64}$')
);

create table if not exists public.modalities (
  id text primary key,
  label text not null,
  description text not null default '',
  sort_order integer not null,
  active boolean not null default true
);

insert into public.modalities (id, label, description, sort_order, active) values
  ('problem-solving','Problem Solving','Write a program that solves the stated problem.',1,true),
  ('debugging','Debugging','Find and fix defects in starter code.',2,true),
  ('code-explanation','Code Explanation','Explain what code does and describe its behavior.',3,true),
  ('code-completion','Code Completion','Complete missing parts of starter code.',4,false)
on conflict (id) do update set
  label = excluded.label,
  description = excluded.description,
  sort_order = excluded.sort_order,
  active = excluded.active;

-- v2.1 modality adjustment: the study uses exactly three modalities.
-- Code Completion remains inactive for backward compatibility; Code Tracing is now Code Explanation.
update public.modalities set active = false where id in ('code-completion', 'code-tracing');

create table if not exists public.study_sessions (
  id uuid primary key default gen_random_uuid(),
  participant_id uuid not null references public.participants(id) on delete restrict,
  language text not null check (language in ('python','java')),
  session_label text not null default 'study-2026',
  randomization_seed text not null,
  status text not null default 'active' check (status in ('active','completed','withdrawn')),
  started_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

create unique index if not exists one_active_session_per_participant
  on public.study_sessions(participant_id) where status = 'active';
create index if not exists study_sessions_language_idx on public.study_sessions(language);
create index if not exists study_sessions_status_idx on public.study_sessions(status);

create table if not exists public.questions (
  id text primary key,
  language text not null check (language in ('python','java')),
  modality_id text not null references public.modalities(id) on delete restrict,
  title text not null,
  prompt text not null,
  starter_code text not null default '',
  difficulty text not null default 'easy' check (difficulty in ('easy','medium','hard')),
  expected_concepts jsonb not null default '[]'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create index if not exists questions_bank_idx on public.questions(language, modality_id, active);

create table if not exists public.question_assignments (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.study_sessions(id) on delete cascade,
  modality_id text not null references public.modalities(id) on delete restrict,
  question_id text not null references public.questions(id) on delete restrict,
  question_order integer not null check (question_order between 1 and 3),
  status text not null default 'assigned' check (status in ('assigned','in_progress','completed')),
  assigned_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  unique(session_id, modality_id, question_order),
  unique(session_id, question_id)
);
create index if not exists assignments_session_idx on public.question_assignments(session_id, modality_id, question_order);

create table if not exists public.submissions (
  id uuid primary key default gen_random_uuid(),
  assignment_id uuid not null unique references public.question_assignments(id) on delete cascade,
  draft_code text,
  draft_explanation text,
  final_code text,
  final_explanation text,
  final_output text,
  status text not null default 'draft' check (status in ('draft','final')),
  first_started_at timestamptz not null default now(),
  saved_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.draft_events (
  id bigint generated by default as identity primary key,
  assignment_id uuid not null references public.question_assignments(id) on delete cascade,
  code_snapshot text,
  explanation_snapshot text,
  client_timestamp timestamptz,
  server_timestamp timestamptz not null default now()
);
create index if not exists draft_events_assignment_idx on public.draft_events(assignment_id, server_timestamp);

create table if not exists public.execution_logs (
  id bigint generated by default as identity primary key,
  assignment_id uuid not null references public.question_assignments(id) on delete cascade,
  language text not null check (language in ('python','java')),
  source_code text not null,
  stdin text,
  stdout text,
  stderr text,
  compile_output text,
  status text not null,
  runtime_ms integer,
  memory_kb integer,
  provider text not null,
  requested_at timestamptz not null default now(),
  completed_at timestamptz
);
create index if not exists execution_logs_assignment_idx on public.execution_logs(assignment_id, requested_at);

create table if not exists public.ai_feedback_logs (
  id bigint generated by default as identity primary key,
  assignment_id uuid not null references public.question_assignments(id) on delete cascade,
  language text not null check (language in ('python','java')),
  modality_id text not null references public.modalities(id) on delete restrict,
  request_number integer not null check (request_number > 0),
  student_code text,
  student_explanation text,
  execution_output text,
  feedback text not null,
  model text not null,
  requested_at timestamptz not null,
  responded_at timestamptz not null,
  latency_ms integer,
  unique(assignment_id, request_number)
);
create index if not exists ai_feedback_assignment_idx on public.ai_feedback_logs(assignment_id, requested_at);

create table if not exists public.modality_completions (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.study_sessions(id) on delete cascade,
  modality_id text not null references public.modalities(id) on delete restrict,
  started_at timestamptz not null,
  completed_at timestamptz not null,
  duration_seconds integer not null check (duration_seconds >= 0),
  unique(session_id, modality_id)
);
create index if not exists modality_completions_session_idx on public.modality_completions(session_id);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.study_sessions(id) on delete cascade,
  assignment_id uuid references public.question_assignments(id) on delete cascade,
  event_type text not null,
  event_data jsonb not null default '{}'::jsonb,
  client_timestamp timestamptz,
  server_timestamp timestamptz not null default now()
);
create index if not exists analytics_events_session_idx on public.analytics_events(session_id, server_timestamp);
create index if not exists analytics_events_type_idx on public.analytics_events(event_type);

-- RLS: participant browsers never access Supabase directly. The Render backend must
-- use a Supabase Secret key (or legacy service_role key), which bypasses RLS.
alter table public.participants enable row level security;
alter table public.modalities enable row level security;
alter table public.study_sessions enable row level security;
alter table public.questions enable row level security;
alter table public.question_assignments enable row level security;
alter table public.submissions enable row level security;
alter table public.draft_events enable row level security;
alter table public.execution_logs enable row level security;
alter table public.ai_feedback_logs enable row level security;
alter table public.modality_completions enable row level security;
alter table public.analytics_events enable row level security;

-- Questions are seeded below. The active study has 20 questions per modality per language (120 active total).
-- Legacy Code Completion questions remain seeded but inactive through their modality.
insert into public.questions
  (id, language, modality_id, title, prompt, starter_code, difficulty, expected_concepts, active)
values
('PY-PS-01','python','problem-solving','Print 1 to 5','Write a program that prints the integers 1 through 5, one per line.','','easy','["for loop", "range"]'::jsonb,true),
('PY-PS-02','python','problem-solving','Sum 1 to 10','Compute and print the sum of the integers 1 through 10.','','easy','["loop", "accumulator"]'::jsonb,true),
('PY-PS-03','python','problem-solving','Even numbers','Print all even numbers from 2 through 20, one per line.','','easy','["loop", "modulo"]'::jsonb,true),
('PY-PS-04','python','problem-solving','Count vowels','Given text = "programming", count and print the number of vowels.','text = "programming"
','easy','["string", "loop", "condition"]'::jsonb,true),
('PY-PS-05','python','problem-solving','Largest value','Given nums = [4, 9, 2, 7, 5], print the largest value without using max().','nums = [4, 9, 2, 7, 5]
','easy','["list", "loop", "comparison"]'::jsonb,true),
('PY-PS-06','python','problem-solving','Factorial','Compute and print 5 factorial using a loop.','','easy','["loop", "accumulator"]'::jsonb,true),
('PY-PS-07','python','problem-solving','Reverse text','Given text = "hello", build and print the reversed string without using slicing.','text = "hello"
','easy','["string", "loop"]'::jsonb,true),
('PY-PS-08','python','problem-solving','Count positives','Given nums = [-2, 4, 0, 7, -1, 3], count and print how many values are positive.','nums = [-2, 4, 0, 7, -1, 3]
','easy','["list", "condition", "counter"]'::jsonb,true),
('PY-PS-09','python','problem-solving','Squares','Print the square of each integer from 1 through 6.','','easy','["loop", "arithmetic"]'::jsonb,true),
('PY-PS-10','python','problem-solving','Running total','Given nums = [3, 1, 4, 2], print the running total after each value.','nums = [3, 1, 4, 2]
','easy','["loop", "accumulator"]'::jsonb,true),
('PY-PS-11','python','problem-solving','Multiplication table','Print the first five multiples of 7.','','medium','["loop", "multiplication"]'::jsonb,true),
('PY-PS-12','python','problem-solving','Count letter','Given text = "banana", count and print how many times the letter ''a'' occurs.','text = "banana"
','medium','["string", "counter"]'::jsonb,true),
('PY-PS-13','python','problem-solving','Minimum value','Given nums = [8, 3, 6, 1, 9], print the smallest value without using min().','nums = [8, 3, 6, 1, 9]
','medium','["list", "comparison"]'::jsonb,true),
('PY-PS-14','python','problem-solving','Sum evens','Compute and print the sum of all even integers from 1 through 20.','','medium','["loop", "condition", "accumulator"]'::jsonb,true),
('PY-PS-15','python','problem-solving','List lengths','Given words = ["cat", "tiger", "ox"], print each word followed by its length.','words = ["cat", "tiger", "ox"]
','medium','["list", "string"]'::jsonb,true),
('PY-PS-16','python','problem-solving','Temperature labels','Given temps = [35, 72, 90], print ''cold'' for values below 50, ''warm'' for 50-79, and ''hot'' for 80 or higher.','temps = [35, 72, 90]
','medium','["conditionals", "loop"]'::jsonb,true),
('PY-PS-17','python','problem-solving','Skip multiples of 3','Print integers 1 through 12 except multiples of 3.','','medium','["loop", "continue", "modulo"]'::jsonb,true),
('PY-PS-18','python','problem-solving','First matching value','Given nums = [3, 5, 8, 10], print the first even number and then stop searching.','nums = [3, 5, 8, 10]
','medium','["loop", "break"]'::jsonb,true),
('PY-PS-19','python','problem-solving','Average','Given nums = [6, 8, 10, 12], compute and print their average using a loop.','nums = [6, 8, 10, 12]
','medium','["loop", "average"]'::jsonb,true),
('PY-PS-20','python','problem-solving','Character positions','Given text = "code", print each character with its zero-based index.','text = "code"
','medium','["enumeration", "string"]'::jsonb,true),
('PY-DBG-01','python','debugging','Off-by-one range','Fix the program so it prints 1 through 5.','for n in range(1, 5):
    print(n)
','easy','["debugging"]'::jsonb,true),
('PY-DBG-02','python','debugging','Missing colon','Fix the syntax error.','for n in range(3)
    print(n)
','easy','["debugging"]'::jsonb,true),
('PY-DBG-03','python','debugging','Indentation error','Fix the indentation so the loop prints each value.','for n in range(3):
print(n)
','easy','["debugging"]'::jsonb,true),
('PY-DBG-04','python','debugging','Wrong accumulator','Fix the program so it prints 15.','total = 0
for n in range(1, 6):
    total = n
print(total)
','easy','["debugging"]'::jsonb,true),
('PY-DBG-05','python','debugging','String integer mix','Fix the program so it prints Age: 20.','age = 20
print("Age: " + age)
','easy','["debugging"]'::jsonb,true),
('PY-DBG-06','python','debugging','Wrong comparison','Fix the program so it prints only positive values.','nums = [-1, 2, -3, 4]
for n in nums:
    if n < 0:
        print(n)
','easy','["debugging"]'::jsonb,true),
('PY-DBG-07','python','debugging','Infinite loop','Fix the loop so it prints 1, 2, 3 and stops.','n = 1
while n <= 3:
    print(n)
','easy','["debugging"]'::jsonb,true),
('PY-DBG-08','python','debugging','Wrong list index','Fix the program so it prints the last item.','items = [10, 20, 30]
print(items[3])
','easy','["debugging"]'::jsonb,true),
('PY-DBG-09','python','debugging','Case mismatch','Fix the condition so the program prints Yes.','answer = "yes"
if answer == "Yes":
    print("Yes")
','easy','["debugging"]'::jsonb,true),
('PY-DBG-10','python','debugging','Wrong boolean operator','Fix the condition so 15 is recognized as being between 10 and 20 inclusive.','x = 15
if x >= 10 or x <= 20:
    print("between")
','easy','["debugging"]'::jsonb,true),
('PY-DBG-11','python','debugging','Average denominator','Fix the average calculation.','nums = [2, 4, 6, 8]
total = sum(nums)
average = total / 3
print(average)
','medium','["debugging"]'::jsonb,true),
('PY-DBG-12','python','debugging','Function return','Fix the function so result becomes 10.','def double(x):
    x * 2

result = double(5)
print(result)
','medium','["debugging"]'::jsonb,true),
('PY-DBG-13','python','debugging','Wrong loop target','Fix the code so it prints each word, not each character of the first word.','words = ["red", "blue"]
for word in words[0]:
    print(word)
','medium','["debugging"]'::jsonb,true),
('PY-DBG-14','python','debugging','Modulo bug','Fix the code so it prints even numbers.','for n in range(1, 7):
    if n % 2 == 1:
        print(n)
','medium','["debugging"]'::jsonb,true),
('PY-DBG-15','python','debugging','Wrong initialization','Fix the maximum-finding logic.','nums = [-8, -3, -12]
largest = 0
for n in nums:
    if n > largest:
        largest = n
print(largest)
','medium','["debugging"]'::jsonb,true),
('PY-DBG-16','python','debugging','Append call','Fix the code so 3 is added to the list.','values = [1, 2]
values.append[3]
print(values)
','medium','["debugging"]'::jsonb,true),
('PY-DBG-17','python','debugging','Key lookup','Fix the dictionary key error.','student = {"name": "Ada"}
print(student["Name"])
','medium','["debugging"]'::jsonb,true),
('PY-DBG-18','python','debugging','Loop boundary','Fix the code so it prints indexes 0, 1, and 2 without an IndexError.','items = ["a", "b", "c"]
for i in range(4):
    print(items[i])
','medium','["debugging"]'::jsonb,true),
('PY-DBG-19','python','debugging','Integer input','Fix the code so adding 1 works when the input is 5.','value = input()
print(value + 1)
','medium','["debugging"]'::jsonb,true),
('PY-DBG-20','python','debugging','Nested indentation','Fix the code so only even values print ''even''.','for n in range(1, 5):
    if n % 2 == 0:
        print(n)
    print("even")
','medium','["debugging"]'::jsonb,true),
('PY-TRC-01','python','code-explanation','Trace a range','Without running the code first, state exactly what it prints.','for n in range(1, 4):
    print(n)
','easy','["tracing"]'::jsonb,true),
('PY-TRC-02','python','code-explanation','Trace accumulator','Predict the final output.','total = 0
for n in [2, 3, 4]:
    total += n
print(total)
','easy','["tracing"]'::jsonb,true),
('PY-TRC-03','python','code-explanation','Trace condition','Predict the output in order.','for n in range(5):
    if n % 2 == 0:
        print(n)
','easy','["tracing"]'::jsonb,true),
('PY-TRC-04','python','code-explanation','Trace string','Predict the output.','text = "cat"
for ch in text:
    print(ch.upper())
','easy','["tracing"]'::jsonb,true),
('PY-TRC-05','python','code-explanation','Trace while','Predict the output.','x = 3
while x > 0:
    print(x)
    x -= 1
','easy','["tracing"]'::jsonb,true),
('PY-TRC-06','python','code-explanation','Trace break','Predict the output.','for n in range(1, 6):
    if n == 4:
        break
    print(n)
','easy','["tracing"]'::jsonb,true),
('PY-TRC-07','python','code-explanation','Trace continue','Predict the output.','for n in range(1, 6):
    if n == 3:
        continue
    print(n)
','easy','["tracing"]'::jsonb,true),
('PY-TRC-08','python','code-explanation','Trace nested loop','How many times is X printed? Also state the printed lines.','for i in range(2):
    for j in range(2):
        print("X")
','easy','["tracing"]'::jsonb,true),
('PY-TRC-09','python','code-explanation','Trace list mutation','Predict the final list.','values = [1, 2]
for n in [3, 4]:
    values.append(n)
print(values)
','easy','["tracing"]'::jsonb,true),
('PY-TRC-10','python','code-explanation','Trace variable update','Predict the output.','x = 1
for _ in range(3):
    x *= 2
print(x)
','easy','["tracing"]'::jsonb,true),
('PY-TRC-11','python','code-explanation','Trace enumerate','Predict the output lines.','for i, ch in enumerate("ab"):
    print(i, ch)
','medium','["tracing"]'::jsonb,true),
('PY-TRC-12','python','code-explanation','Trace membership','Predict the output.','items = [2, 4, 6]
print(4 in items)
print(5 in items)
','medium','["tracing"]'::jsonb,true),
('PY-TRC-13','python','code-explanation','Trace function','Predict the output.','def add_one(x):
    return x + 1

print(add_one(4))
','medium','["tracing"]'::jsonb,true),
('PY-TRC-14','python','code-explanation','Trace slicing','Predict the output.','text = "python"
print(text[1:4])
','medium','["tracing"]'::jsonb,true),
('PY-TRC-15','python','code-explanation','Trace dictionary','Predict the output.','d = {"a": 2, "b": 3}
print(d["a"] + d["b"])
','medium','["tracing"]'::jsonb,true),
('PY-TRC-16','python','code-explanation','Trace comparison','Predict the output.','x = 7
if x > 5 and x < 10:
    print("A")
else:
    print("B")
','medium','["tracing"]'::jsonb,true),
('PY-TRC-17','python','code-explanation','Trace sum loop','Predict the final output.','s = 1
for n in range(1, 4):
    s += n
print(s)
','medium','["tracing"]'::jsonb,true),
('PY-TRC-18','python','code-explanation','Trace reversed','Predict the output sequence.','for n in reversed([1, 2, 3]):
    print(n)
','medium','["tracing"]'::jsonb,true),
('PY-TRC-19','python','code-explanation','Trace length','Predict the output.','words = ["hi", "code"]
for w in words:
    print(len(w))
','medium','["tracing"]'::jsonb,true),
('PY-TRC-20','python','code-explanation','Trace nested condition','Predict the output.','for n in [1, 2, 3, 4]:
    if n > 2:
        if n % 2 == 0:
            print(n)
','medium','["tracing"]'::jsonb,true),
('PY-CMP-01','python','code-completion','Complete range','Replace TODO so the loop prints 1 through 5.','for n in range(TODO):
    print(n)
','easy','["completion"]'::jsonb,true),
('PY-CMP-02','python','code-completion','Complete sum','Replace TODO to accumulate the sum.','total = 0
for n in range(1, 6):
    TODO
print(total)
','easy','["completion"]'::jsonb,true),
('PY-CMP-03','python','code-completion','Complete condition','Replace TODO so only even numbers print.','for n in range(1, 7):
    if TODO:
        print(n)
','easy','["completion"]'::jsonb,true),
('PY-CMP-04','python','code-completion','Complete function','Replace TODO with the correct return statement.','def square(x):
    TODO

print(square(4))
','easy','["completion"]'::jsonb,true),
('PY-CMP-05','python','code-completion','Complete list loop','Replace TODO so each item prints.','items = ["a", "b", "c"]
for item in TODO:
    print(item)
','easy','["completion"]'::jsonb,true),
('PY-CMP-06','python','code-completion','Complete counter','Replace TODO so the count increases for positive values.','count = 0
for n in [-1, 2, 3]:
    if n > 0:
        TODO
print(count)
','easy','["completion"]'::jsonb,true),
('PY-CMP-07','python','code-completion','Complete while','Replace TODO so the loop eventually stops.','n = 1
while n <= 3:
    print(n)
    TODO
','easy','["completion"]'::jsonb,true),
('PY-CMP-08','python','code-completion','Complete append','Replace TODO to add 3 to values.','values = [1, 2]
TODO
print(values)
','easy','["completion"]'::jsonb,true),
('PY-CMP-09','python','code-completion','Complete maximum','Replace TODO in the comparison.','nums = [2, 8, 4]
largest = nums[0]
for n in nums:
    if TODO:
        largest = n
print(largest)
','easy','["completion"]'::jsonb,true),
('PY-CMP-10','python','code-completion','Complete string count','Replace TODO so the program counts ''a''.','text = "banana"
count = 0
for ch in text:
    if TODO:
        count += 1
print(count)
','easy','["completion"]'::jsonb,true),
('PY-CMP-11','python','code-completion','Complete input conversion','Replace TODO so numeric addition works.','value = TODO(input())
print(value + 1)
','medium','["completion"]'::jsonb,true),
('PY-CMP-12','python','code-completion','Complete index loop','Replace TODO to iterate valid indexes.','items = [10, 20, 30]
for i in range(TODO):
    print(i, items[i])
','medium','["completion"]'::jsonb,true),
('PY-CMP-13','python','code-completion','Complete average','Replace TODO with the correct denominator.','nums = [2, 4, 6, 8]
average = sum(nums) / TODO
print(average)
','medium','["completion"]'::jsonb,true),
('PY-CMP-14','python','code-completion','Complete break','Replace TODO so the loop stops when n equals 3.','for n in range(1, 6):
    if TODO:
        break
    print(n)
','medium','["completion"]'::jsonb,true),
('PY-CMP-15','python','code-completion','Complete dictionary','Replace TODO with the correct key.','student = {"name": "Ada", "score": 95}
print(student[TODO])
','medium','["completion"]'::jsonb,true),
('PY-CMP-16','python','code-completion','Complete nested loop','Replace TODO so the inner loop runs twice.','for i in range(2):
    for j in range(TODO):
        print(i, j)
','medium','["completion"]'::jsonb,true),
('PY-CMP-17','python','code-completion','Complete boolean','Replace TODO so values 10 through 20 inclusive are accepted.','x = 15
if TODO:
    print("accepted")
','medium','["completion"]'::jsonb,true),
('PY-CMP-18','python','code-completion','Complete reverse build','Replace TODO so reversed_text becomes ''cba''.','text = "abc"
reversed_text = ""
for ch in text:
    TODO
print(reversed_text)
','medium','["completion"]'::jsonb,true),
('PY-CMP-19','python','code-completion','Complete list comprehension','Replace TODO so squares becomes [1, 4, 9, 16].','squares = [TODO for n in range(1, 5)]
print(squares)
','medium','["completion"]'::jsonb,true),
('PY-CMP-20','python','code-completion','Complete return condition','Replace TODO so is_even returns True for even values.','def is_even(n):
    return TODO

print(is_even(6))
','medium','["completion"]'::jsonb,true),
('JA-PS-01','java','problem-solving','Print 1 to 5','Write a Java program that prints the integers 1 through 5, one per line.','public class Main {
    public static void main(String[] args) {
        // Write your code here
    }
}
','easy','["java", "loops"]'::jsonb,true),
('JA-PS-02','java','problem-solving','Sum 1 to 10','Compute and print the sum of the integers 1 through 10.','public class Main {
    public static void main(String[] args) {
        // Write your code here
    }
}
','easy','["java", "loops"]'::jsonb,true),
('JA-PS-03','java','problem-solving','Even numbers','Print all even numbers from 2 through 20, one per line.','public class Main {
    public static void main(String[] args) {
        // Write your code here
    }
}
','easy','["java", "loops"]'::jsonb,true),
('JA-PS-04','java','problem-solving','Count vowels','Given String text = "programming", count and print the number of vowels.','public class Main {
    public static void main(String[] args) {
        // Write your code here
    }
}
','easy','["java", "loops"]'::jsonb,true),
('JA-PS-05','java','problem-solving','Largest value','Given int[] nums = {4, 9, 2, 7, 5}, print the largest value without using library max helpers.','public class Main {
    public static void main(String[] args) {
        // Write your code here
    }
}
','easy','["java", "loops"]'::jsonb,true),
('JA-PS-06','java','problem-solving','Factorial','Compute and print 5 factorial using a loop.','public class Main {
    public static void main(String[] args) {
        // Write your code here
    }
}
','easy','["java", "loops"]'::jsonb,true),
('JA-PS-07','java','problem-solving','Reverse text','Given String text = "hello", build and print the reversed string using a loop.','public class Main {
    public static void main(String[] args) {
        // Write your code here
    }
}
','easy','["java", "loops"]'::jsonb,true),
('JA-PS-08','java','problem-solving','Count positives','Given int[] nums = {-2, 4, 0, 7, -1, 3}, count and print how many values are positive.','public class Main {
    public static void main(String[] args) {
        // Write your code here
    }
}
','easy','["java", "loops"]'::jsonb,true),
('JA-PS-09','java','problem-solving','Squares','Print the square of each integer from 1 through 6.','public class Main {
    public static void main(String[] args) {
        // Write your code here
    }
}
','easy','["java", "loops"]'::jsonb,true),
('JA-PS-10','java','problem-solving','Running total','Given int[] nums = {3, 1, 4, 2}, print the running total after each value.','public class Main {
    public static void main(String[] args) {
        // Write your code here
    }
}
','easy','["java", "loops"]'::jsonb,true),
('JA-PS-11','java','problem-solving','Multiplication table','Print the first five multiples of 7.','public class Main {
    public static void main(String[] args) {
        // Write your code here
    }
}
','medium','["java", "loops"]'::jsonb,true),
('JA-PS-12','java','problem-solving','Count letter','Given String text = "banana", count and print how many times ''a'' occurs.','public class Main {
    public static void main(String[] args) {
        // Write your code here
    }
}
','medium','["java", "loops"]'::jsonb,true),
('JA-PS-13','java','problem-solving','Minimum value','Given int[] nums = {8, 3, 6, 1, 9}, print the smallest value.','public class Main {
    public static void main(String[] args) {
        // Write your code here
    }
}
','medium','["java", "loops"]'::jsonb,true),
('JA-PS-14','java','problem-solving','Sum evens','Compute and print the sum of all even integers from 1 through 20.','public class Main {
    public static void main(String[] args) {
        // Write your code here
    }
}
','medium','["java", "loops"]'::jsonb,true),
('JA-PS-15','java','problem-solving','Word lengths','Given String[] words = {"cat", "tiger", "ox"}, print each word followed by its length.','public class Main {
    public static void main(String[] args) {
        // Write your code here
    }
}
','medium','["java", "loops"]'::jsonb,true),
('JA-PS-16','java','problem-solving','Temperature labels','Given int[] temps = {35, 72, 90}, print cold/warm/hot using the same boundaries: below 50, 50-79, 80+.','public class Main {
    public static void main(String[] args) {
        // Write your code here
    }
}
','medium','["java", "loops"]'::jsonb,true),
('JA-PS-17','java','problem-solving','Skip multiples of 3','Print integers 1 through 12 except multiples of 3.','public class Main {
    public static void main(String[] args) {
        // Write your code here
    }
}
','medium','["java", "loops"]'::jsonb,true),
('JA-PS-18','java','problem-solving','First matching value','Given int[] nums = {3, 5, 8, 10}, print the first even number and stop searching.','public class Main {
    public static void main(String[] args) {
        // Write your code here
    }
}
','medium','["java", "loops"]'::jsonb,true),
('JA-PS-19','java','problem-solving','Average','Given int[] nums = {6, 8, 10, 12}, compute and print their average as a double.','public class Main {
    public static void main(String[] args) {
        // Write your code here
    }
}
','medium','["java", "loops"]'::jsonb,true),
('JA-PS-20','java','problem-solving','Character positions','Given String text = "code", print each character with its zero-based index.','public class Main {
    public static void main(String[] args) {
        // Write your code here
    }
}
','medium','["java", "loops"]'::jsonb,true),
('JA-DBG-01','java','debugging','Off-by-one loop','Fix the loop so it prints 1 through 5.','public class Main { public static void main(String[] args) { for (int n = 1; n < 5; n++) System.out.println(n); } }','easy','["java", "debugging"]'::jsonb,true),
('JA-DBG-02','java','debugging','Missing semicolon','Fix the syntax error.','public class Main { public static void main(String[] args) { int x = 5 System.out.println(x); } }','easy','["java", "debugging"]'::jsonb,true),
('JA-DBG-03','java','debugging','Wrong increment','Fix the loop so it prints 1, 2, 3 and stops.','public class Main { public static void main(String[] args) { for (int n=1; n<=3; n--) System.out.println(n); } }','easy','["java", "debugging"]'::jsonb,true),
('JA-DBG-04','java','debugging','Wrong accumulator','Fix the program so it prints 15.','public class Main { public static void main(String[] args) { int total=0; for(int n=1;n<=5;n++){ total=n; } System.out.println(total); } }','easy','["java", "debugging"]'::jsonb,true),
('JA-DBG-05','java','debugging','String comparison','Fix the condition so it prints Yes.','public class Main { public static void main(String[] args) { String s="yes"; if(s == "yes") System.out.println("Yes"); } }','easy','["java", "debugging"]'::jsonb,true),
('JA-DBG-06','java','debugging','Wrong comparison','Fix the program so it prints only positive values.','public class Main { public static void main(String[] args) { int[] a={-1,2,-3,4}; for(int n:a) if(n<0) System.out.println(n); } }','easy','["java", "debugging"]'::jsonb,true),
('JA-DBG-07','java','debugging','Array bound','Fix the program so it prints the last item.','public class Main { public static void main(String[] args) { int[] a={10,20,30}; System.out.println(a[3]); } }','easy','["java", "debugging"]'::jsonb,true),
('JA-DBG-08','java','debugging','Integer division','Fix the program so it prints 2.5.','public class Main { public static void main(String[] args) { int a=5; int b=2; System.out.println(a/b); } }','easy','["java", "debugging"]'::jsonb,true),
('JA-DBG-09','java','debugging','Assignment in condition','Fix the condition.','public class Main { public static void main(String[] args) { int x=5; if(x = 5) System.out.println("five"); } }','easy','["java", "debugging"]'::jsonb,true),
('JA-DBG-10','java','debugging','Wrong boolean operator','Fix the condition so only values from 10 through 20 inclusive are accepted.','public class Main { public static void main(String[] args) { int x=25; if(x>=10 || x<=20) System.out.println("between"); } }','easy','["java", "debugging"]'::jsonb,true),
('JA-DBG-11','java','debugging','Average denominator','Fix the average calculation.','public class Main { public static void main(String[] args) { int[] a={2,4,6,8}; int total=0; for(int n:a) total+=n; double avg=total/3.0; System.out.println(avg); } }','medium','["java", "debugging"]'::jsonb,true),
('JA-DBG-12','java','debugging','Missing return','Fix the method so result becomes 10.','public class Main { static int twice(int x){ x*2; } public static void main(String[] args){ System.out.println(twice(5)); } }','medium','["java", "debugging"]'::jsonb,true),
('JA-DBG-13','java','debugging','Wrong loop index','Fix the loop so every array element prints without error.','public class Main { public static void main(String[] args){ int[] a={1,2,3}; for(int i=0;i<=a.length;i++) System.out.println(a[i]); } }','medium','["java", "debugging"]'::jsonb,true),
('JA-DBG-14','java','debugging','Modulo bug','Fix the code so it prints even numbers.','public class Main { public static void main(String[] args){ for(int n=1;n<=6;n++) if(n%2==1) System.out.println(n); } }','medium','["java", "debugging"]'::jsonb,true),
('JA-DBG-15','java','debugging','Maximum initialization','Fix the maximum logic for all-negative input.','public class Main { public static void main(String[] args){ int[] a={-8,-3,-12}; int largest=0; for(int n:a) if(n>largest) largest=n; System.out.println(largest); } }','medium','["java", "debugging"]'::jsonb,true),
('JA-DBG-16','java','debugging','Array length','Fix the property/method error.','public class Main { public static void main(String[] args){ int[] a={1,2,3}; System.out.println(a.length()); } }','medium','["java", "debugging"]'::jsonb,true),
('JA-DBG-17','java','debugging','Character method','Fix the code so it prints the first character.','public class Main { public static void main(String[] args){ String s="code"; System.out.println(s[0]); } }','medium','["java", "debugging"]'::jsonb,true),
('JA-DBG-18','java','debugging','Parse input','Fix the code so numeric addition works.','import java.util.*; public class Main { public static void main(String[] args){ Scanner sc=new Scanner(System.in); String x=sc.nextLine(); System.out.println(x+1); } }','medium','["java", "debugging"]'::jsonb,true),
('JA-DBG-19','java','debugging','Scope error','Fix the code so total can be printed after the loop.','public class Main { public static void main(String[] args){ for(int i=0;i<3;i++){ int total=i; } System.out.println(total); } }','medium','["java", "debugging"]'::jsonb,true),
('JA-DBG-20','java','debugging','Nested braces','Fix the braces so ''even'' prints only for even values.','public class Main { public static void main(String[] args){ for(int n=1;n<=4;n++){ if(n%2==0) System.out.println(n); } System.out.println("even"); } }','medium','["java", "debugging"]'::jsonb,true),
('JA-TRC-01','java','code-explanation','Trace a loop','Without running the code first, state exactly what it prints.','public class Main { public static void main(String[] args){ for(int n=1;n<=3;n++) System.out.println(n); } }','easy','["java", "tracing"]'::jsonb,true),
('JA-TRC-02','java','code-explanation','Trace accumulator','Predict the final output.','public class Main { public static void main(String[] args){ int total=0; for(int n:new int[]{2,3,4}) total+=n; System.out.println(total); } }','easy','["java", "tracing"]'::jsonb,true),
('JA-TRC-03','java','code-explanation','Trace condition','Predict the output in order.','public class Main { public static void main(String[] args){ for(int n=0;n<5;n++) if(n%2==0) System.out.println(n); } }','easy','["java", "tracing"]'::jsonb,true),
('JA-TRC-04','java','code-explanation','Trace string','Predict the output.','public class Main { public static void main(String[] args){ String s="cat"; for(int i=0;i<s.length();i++) System.out.println(Character.toUpperCase(s.charAt(i))); } }','easy','["java", "tracing"]'::jsonb,true),
('JA-TRC-05','java','code-explanation','Trace while','Predict the output.','public class Main { public static void main(String[] args){ int x=3; while(x>0){ System.out.println(x); x--; } } }','easy','["java", "tracing"]'::jsonb,true),
('JA-TRC-06','java','code-explanation','Trace break','Predict the output.','public class Main { public static void main(String[] args){ for(int n=1;n<=5;n++){ if(n==4) break; System.out.println(n); } } }','easy','["java", "tracing"]'::jsonb,true),
('JA-TRC-07','java','code-explanation','Trace continue','Predict the output.','public class Main { public static void main(String[] args){ for(int n=1;n<=5;n++){ if(n==3) continue; System.out.println(n); } } }','easy','["java", "tracing"]'::jsonb,true),
('JA-TRC-08','java','code-explanation','Trace nested loop','How many times is X printed?','public class Main { public static void main(String[] args){ for(int i=0;i<2;i++) for(int j=0;j<2;j++) System.out.println("X"); } }','easy','["java", "tracing"]'::jsonb,true),
('JA-TRC-09','java','code-explanation','Trace array update','Predict the final output.','public class Main { public static void main(String[] args){ int[] a={1,2,3}; a[1]=9; System.out.println(a[0]+" "+a[1]+" "+a[2]); } }','easy','["java", "tracing"]'::jsonb,true),
('JA-TRC-10','java','code-explanation','Trace doubling','Predict the output.','public class Main { public static void main(String[] args){ int x=1; for(int i=0;i<3;i++) x*=2; System.out.println(x); } }','easy','["java", "tracing"]'::jsonb,true),
('JA-TRC-11','java','code-explanation','Trace index','Predict the output lines.','public class Main { public static void main(String[] args){ String s="ab"; for(int i=0;i<s.length();i++) System.out.println(i+" "+s.charAt(i)); } }','medium','["java", "tracing"]'::jsonb,true),
('JA-TRC-12','java','code-explanation','Trace boolean','Predict the output.','public class Main { public static void main(String[] args){ int x=4; System.out.println(x>2 && x<6); System.out.println(x==5); } }','medium','["java", "tracing"]'::jsonb,true),
('JA-TRC-13','java','code-explanation','Trace method','Predict the output.','public class Main { static int addOne(int x){ return x+1; } public static void main(String[] args){ System.out.println(addOne(4)); } }','medium','["java", "tracing"]'::jsonb,true),
('JA-TRC-14','java','code-explanation','Trace substring','Predict the output.','public class Main { public static void main(String[] args){ String s="python"; System.out.println(s.substring(1,4)); } }','medium','["java", "tracing"]'::jsonb,true),
('JA-TRC-15','java','code-explanation','Trace array length','Predict the output.','public class Main { public static void main(String[] args){ int[] a={4,5,6}; System.out.println(a.length); } }','medium','["java", "tracing"]'::jsonb,true),
('JA-TRC-16','java','code-explanation','Trace comparison','Predict the output.','public class Main { public static void main(String[] args){ int x=7; if(x>5 && x<10) System.out.println("A"); else System.out.println("B"); } }','medium','["java", "tracing"]'::jsonb,true),
('JA-TRC-17','java','code-explanation','Trace sum loop','Predict the final output.','public class Main { public static void main(String[] args){ int s=1; for(int n=1;n<=3;n++) s+=n; System.out.println(s); } }','medium','["java", "tracing"]'::jsonb,true),
('JA-TRC-18','java','code-explanation','Trace reverse index','Predict the output sequence.','public class Main { public static void main(String[] args){ int[] a={1,2,3}; for(int i=a.length-1;i>=0;i--) System.out.println(a[i]); } }','medium','["java", "tracing"]'::jsonb,true),
('JA-TRC-19','java','code-explanation','Trace word lengths','Predict the output.','public class Main { public static void main(String[] args){ String[] w={"hi","code"}; for(String s:w) System.out.println(s.length()); } }','medium','["java", "tracing"]'::jsonb,true),
('JA-TRC-20','java','code-explanation','Trace nested condition','Predict the output.','public class Main { public static void main(String[] args){ for(int n:new int[]{1,2,3,4}) if(n>2) if(n%2==0) System.out.println(n); } }','medium','["java", "tracing"]'::jsonb,true),
('JA-CMP-01','java','code-completion','Complete loop bound','Replace TODO so the loop prints 1 through 5.','public class Main { public static void main(String[] args){ for(int n=1;n<=TODO;n++) System.out.println(n); } }','easy','["java", "completion"]'::jsonb,true),
('JA-CMP-02','java','code-completion','Complete sum','Replace TODO to accumulate the sum.','public class Main { public static void main(String[] args){ int total=0; for(int n=1;n<=5;n++){ TODO } System.out.println(total); } }','easy','["java", "completion"]'::jsonb,true),
('JA-CMP-03','java','code-completion','Complete condition','Replace TODO so only even numbers print.','public class Main { public static void main(String[] args){ for(int n=1;n<=6;n++) if(TODO) System.out.println(n); } }','easy','["java", "completion"]'::jsonb,true),
('JA-CMP-04','java','code-completion','Complete method','Replace TODO with the correct return statement.','public class Main { static int square(int x){ TODO } public static void main(String[] args){ System.out.println(square(4)); } }','easy','["java", "completion"]'::jsonb,true),
('JA-CMP-05','java','code-completion','Complete enhanced loop','Replace TODO so each item prints.','public class Main { public static void main(String[] args){ String[] items={"a","b","c"}; for(String item : TODO) System.out.println(item); } }','easy','["java", "completion"]'::jsonb,true),
('JA-CMP-06','java','code-completion','Complete counter','Replace TODO so count increases for positive values.','public class Main { public static void main(String[] args){ int count=0; for(int n:new int[]{-1,2,3}) if(n>0){ TODO } System.out.println(count); } }','easy','["java", "completion"]'::jsonb,true),
('JA-CMP-07','java','code-completion','Complete while','Replace TODO so the loop stops after printing 1,2,3.','public class Main { public static void main(String[] args){ int n=1; while(n<=3){ System.out.println(n); TODO } } }','easy','["java", "completion"]'::jsonb,true),
('JA-CMP-08','java','code-completion','Complete array assignment','Replace TODO so the second element becomes 9.','public class Main { public static void main(String[] args){ int[] a={1,2,3}; TODO; System.out.println(a[1]); } }','easy','["java", "completion"]'::jsonb,true),
('JA-CMP-09','java','code-completion','Complete maximum','Replace TODO in the comparison.','public class Main { public static void main(String[] args){ int[] a={2,8,4}; int largest=a[0]; for(int n:a) if(TODO) largest=n; System.out.println(largest); } }','easy','["java", "completion"]'::jsonb,true),
('JA-CMP-10','java','code-completion','Complete string count','Replace TODO so the program counts ''a''.','public class Main { public static void main(String[] args){ String s="banana"; int count=0; for(int i=0;i<s.length();i++) if(TODO) count++; System.out.println(count); } }','easy','["java", "completion"]'::jsonb,true),
('JA-CMP-11','java','code-completion','Complete parsing','Replace TODO so numeric addition works.','import java.util.*; public class Main { public static void main(String[] args){ Scanner sc=new Scanner(System.in); int x=TODO(sc.nextLine()); System.out.println(x+1); } }','medium','["java", "completion"]'::jsonb,true),
('JA-CMP-12','java','code-completion','Complete index loop','Replace TODO to iterate valid indexes.','public class Main { public static void main(String[] args){ int[] a={10,20,30}; for(int i=0;i<TODO;i++) System.out.println(i+" "+a[i]); } }','medium','["java", "completion"]'::jsonb,true),
('JA-CMP-13','java','code-completion','Complete average','Replace TODO so the result is a double average.','public class Main { public static void main(String[] args){ int[] a={2,4,6,8}; int total=20; double avg=TODO; System.out.println(avg); } }','medium','["java", "completion"]'::jsonb,true),
('JA-CMP-14','java','code-completion','Complete break','Replace TODO so the loop stops when n equals 3.','public class Main { public static void main(String[] args){ for(int n=1;n<=5;n++){ if(TODO) break; System.out.println(n); } } }','medium','["java", "completion"]'::jsonb,true),
('JA-CMP-15','java','code-completion','Complete map lookup','Replace TODO to print Ada.','import java.util.*; public class Main { public static void main(String[] args){ Map<String,String> m=new HashMap<>(); m.put("name","Ada"); System.out.println(m.get(TODO)); } }','medium','["java", "completion"]'::jsonb,true),
('JA-CMP-16','java','code-completion','Complete nested loop','Replace TODO so the inner loop runs twice.','public class Main { public static void main(String[] args){ for(int i=0;i<2;i++) for(int j=0;j<TODO;j++) System.out.println(i+" "+j); } }','medium','["java", "completion"]'::jsonb,true),
('JA-CMP-17','java','code-completion','Complete boolean','Replace TODO so values 10 through 20 inclusive are accepted.','public class Main { public static void main(String[] args){ int x=15; if(TODO) System.out.println("accepted"); } }','medium','["java", "completion"]'::jsonb,true),
('JA-CMP-18','java','code-completion','Complete reverse build','Replace TODO so out becomes cba.','public class Main { public static void main(String[] args){ String s="abc", out=""; for(int i=0;i<s.length();i++){ TODO } System.out.println(out); } }','medium','["java", "completion"]'::jsonb,true),
('JA-CMP-19','java','code-completion','Complete ArrayList add','Replace TODO so 3 is appended.','import java.util.*; public class Main { public static void main(String[] args){ List<Integer> a=new ArrayList<>(); a.add(1); a.add(2); TODO; System.out.println(a); } }','medium','["java", "completion"]'::jsonb,true),
('JA-CMP-20','java','code-completion','Complete even method','Replace TODO so isEven returns true for even values.','public class Main { static boolean isEven(int n){ return TODO; } public static void main(String[] args){ System.out.println(isEven(6)); } }','medium','["java", "completion"]'::jsonb,true)
on conflict (id) do update set
  language = excluded.language,
  modality_id = excluded.modality_id,
  title = excluded.title,
  prompt = excluded.prompt,
  starter_code = excluded.starter_code,
  difficulty = excluded.difficulty,
  expected_concepts = excluded.expected_concepts,
  active = excluded.active;

-- Keep the retired Code Completion bank unavailable to study sessions.
update public.questions set active = false where modality_id = 'code-completion';

-- Helpful integrity check. Expected: 6 rows, each with question_count = 20 (120 active questions total).
select language, modality_id, count(*) as question_count
from public.questions
where active = true
group by language, modality_id
order by language, modality_id;
